name: 🚀 Deploy to Github Pages (taiga-ui.dev)
on:
  workflow_run:
    workflows: ['🚀 Snapshots']
    types:
      - completed
  workflow_dispatch:
    inputs:
      dryRun:
        type: boolean
        required: false
        description: --dry-run

jobs:
  deploy-gh-pages:
    if: ${{ !contains(github.event.workflow_run.head_branch, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.60.1
      - uses: taiga-family/ci/actions/setup/variables@v1.60.1

      - name: Prepare demo before deploy from snapshots
        run: |
          git clone --depth 1 --branch snapshots/demo/v3.x ${{ env.REPO }} ${{ env.DIST }}
          git clone --depth 1 --branch snapshots/demo/v2.x ${{ env.REPO }} ${{ env.DIST }}/v2
          git clone --depth 1 --branch snapshots/demo/next/main ${{ env.REPO }} ${{ env.DIST }}/next

      - name: Cleanup after clone snapshots
        run: find ${{ env.DIST }} -name ".git" -exec rm -rf {} \; > /dev/null 2>&1 || echo "removed .git"

      - name: Debug output
        run: tree ${{ env.DIST }} -P '*.html'

      - name: Deploy to taiga-ui.dev
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: ${{ github.event.inputs.dryRun != 'true' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.DIST }}

concurrency:
  group: deploy-gh-pages
  cancel-in-progress: true
